# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41c6acfde6b943cbf242d3c881c63756e856b3ff615e7407027c5624f924f6746dfe8d51c29f41367c2b24be0c730816e7d3abe4995d7ed8d48bf6cce229e27c

test:
  secret_key_base: 405b5b21a8bb4d37b30537d26dc6efbf7e566c8424167574379f747b689de22213f4b41a5415dd69143eea82684e01a1fd2622504819011882f1626c1fb29ca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
